language: php

services:
  - mysql

php:
  - 7.1

sudo: false

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

install:
  - composer install --prefer-dist --optimize-autoloader --quiet
  - cp .env.travis .env
  - php artisan key:generate

script:
  - ./vendor/edgedesign/phpqa/phpqa --output cli --ignoredDirs bootstrap,database,resource,storage,vendor --tools phpcs:0,phpmd:2,phpcpd:0,phpmetrics,pdepend
  - phpunit -c phpunit.xml --coverage-text

notifications:
  email:
    recipients:
      - s1410432005@gms.nutc.edu.tw
    on_success: always
    on_failure: always
