language: php

php:
  - 7.1

sudo: false

install:
  - composer install --prefer-dist --optimize-autoloader --quiet
  - php artisan key:generate

script: phpunit -c phpunit.xml --coverage-text

notifications:
  email:
    recipients:
      - s1410432005@gms.nutc.edu.tw
    on_success: always
    on_failure: always