language: php

services:
  - mysql

php:
  - 7.1

sudo: false

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

install:
  - composer install --prefer-dist --optimize-autoloader --quiet
  - cp .env.travis .env
  - php artisan key:generate

script:
  - ./vendor/edgedesign/phpqa/phpqa --ignoredDirs bootstrap,vendor --tools phpcs:5,phpmd:2,phpcpd:0,parallel-lint:0,phpstan:0,phpmetrics,phploc,pdepend
  - phpunit -c phpunit.xml --coverage-text
  - vendor/squizlabs/php_codesniffer/bin/phpcs -p --extensions=php --standard=PSR2  --ignore=*/bootstrap/*,*/vendor/* "./"

notifications:
  email:
    recipients:
      - s1410432005@gms.nutc.edu.tw
    on_success: always
    on_failure: always
